/**
 * The land, as an even field of dots.
 *
 * lib/globe/land.ts holds a 1-degree land/sea bitmask (10.5 KB, generated by
 * scripts/gen-land-mask.mjs). Dots sit on rings of latitude with as many dots per ring as its
 * circumference allows, so spacing stays even from the equator to the poles, and the ones that
 * fall on land are kept. Changing the density costs nothing but a redraw.
 *
 * A Fibonacci spiral spaces points more evenly still, but drew visible spiral arcs across the
 * Arctic once projected - an artefact the eye reads as a pattern in the map rather than as land.
 */
import { LAND_COLS, LAND_MASK_BASE64, LAND_ROWS } from "./land";

let mask: Uint8Array | null = null;

function maskBytes(): Uint8Array {
  if (mask) return mask;
  const binary = atob(LAND_MASK_BASE64);
  const bytes = new Uint8Array(binary.length);
  for (let i = 0; i < binary.length; i++) bytes[i] = binary.charCodeAt(i);
  mask = bytes;
  return bytes;
}

export function isLand(lng: number, lat: number): boolean {
  const row = Math.min(LAND_ROWS - 1, Math.max(0, Math.floor(90 - lat)));
  const col = Math.min(LAND_COLS - 1, Math.max(0, Math.floor(lng + 180)));
  const bit = row * LAND_COLS + col;
  return (maskBytes()[bit >> 3] & (0x80 >> (bit & 7))) !== 0;
}

const RAD = Math.PI / 180;

/**
 * Land dots spaced roughly `spacingDeg` degrees apart in both directions.
 * Returns a flat [lng, lat, lng, lat, ...] array; about a third of the candidates are land.
 */
export function landDots(spacingDeg = 1.3): Float32Array {
  const out: number[] = [];
  let ring = 0;
  for (let lat = -89 + spacingDeg / 2; lat < 90; lat += spacingDeg, ring++) {
    // Fewer dots as the rings shrink toward the poles, so the spacing on the ground stays even.
    const count = Math.max(1, Math.round((360 / spacingDeg) * Math.cos(lat * RAD)));
    const step = 360 / count;
    // Half a step of offset on alternate rings, or the dots line up into vertical seams.
    const offset = (ring % 2) * (step / 2);
    for (let i = 0; i < count; i++) {
      const lng = -180 + i * step + offset;
      if (!isLand(lng, lat)) continue;
      out.push(lng, lat);
    }
  }
  return Float32Array.from(out);
}
